# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fee970a438822e9563d696687e49cc11d8257869faa692f7659e226a7cf29134560f4004aad2f1e204c8537b537645c935ff903a2e73b57ffad111b7e269ee24

test:
  secret_key_base: bf98ba66094bce63a1a154f53578344864e9958a94195f4a8c2fb1854352abbb49ed976fc47a83e495ab87af818b12c3b2ef86306a572e9f519b0874218b1ada

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
